#install.packages("RSQLite")
install.packages("RPostgreSQL", dependencies = TRUE)
install.packages("DBI")
install.packages("methods")
#install.packages("dplyr")
#install.packages("dbplyr")
#install.packages("ggplot2")
#install.packages("pitchRx")
#install.packages("stringr")