platform: linux

image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-cli
    tag: latest

inputs:
- name: mlb-datafresh
params:
  CF_USER:
  CF_PASSWORD:
  CF_ORG:
  CF_SPACE:
# outputs:
# - name:

run:
  path: /bin/bash
  args:
    - -exc
    - |
      cf login -a api.run.pivotal.io -u $CF_USER -p $CF_PASSWORD -o $CF_ORG -s $CF_SPACE
      taskname=$(cf run-task MLB-DatafreshAnt "R -f 00-mlb-datafresh.R" | grep "task name" | cut -f2 -d: | xargs echo -n)
      IsRunning=$(cf tasks MLB-DatafreshAnt | grep "$taskname" | grep 'RUNNING')
      echo ${IsRunning}
      while [[ ${IsRunning} ]] ; do
      sleep 10
      IsRunning=$(cf tasks MLB-DatafreshAnt | grep "$taskname" | grep 'RUNNING' || true)
      echo ${IsRunning}
      done
      echo done processing