platform: linux

image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-cli
    tag: latest

inputs:
- name: mlb-datafresh
params:
  CF_USER:
  CF_PASSWORD:
  CF_ORG:
  CF_SPACE:
# outputs:
# - name:

run:
  path: /bin/bash
  args:
    - -exc
    - |
      cf login -a api.run.pivotal.io -u $CF_USER -p $CF_PASSWORD -o $CF_ORG -s $CF_SPACE
      taskname=$(cf run-task MLB-DatafreshAnt "R -f 00-mlb-datafresh.R" | grep "task name" | cut -f2 -d: | xargs echo -n)
      RUNNING=$(cf tasks MLB-DatafreshAnt | grep "$taskname" | grep 'RUNNING')
      echo ${RUNNING}
      while [[ ${RUNNING} ]] ; do
      sleep 30
      LOGS=$(cf logs MLB-DatafreshAnt --recent | grep "$taskname" | tail -n20)
      echo ${RUNNING}
      echo ${LOGS}
      RUNNING=$(cf tasks MLB-DatafreshAnt | grep "$taskname" | grep 'RUNNING')
      sleep 30
      done
      SUCCEEDED=$(cf tasks MLB-DatafreshAnt | grep "$taskname" | grep 'SUCCEEDED')
      echo ${SUCCEEDED}
      echo done processing